# Data Cleaning Step

The purpose of this notebook is to document the steps to clean up the dataset to prepare it for future analysis. The notebook will follow the following cleaning steps:

1. coerce passenger count into integer data types
2. remove those rows with questionable pick up and drop off times
3. remove the rows where the drop off time is earlier than the pick up time
4. remove the rows where the pick up time is outside of Jan

In [1]:
# Imports

import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Read in the files

df = pd.read_parquet("../data/raw/yellow_tripdata_2026-01.parquet")
taxi_zone = pd.read_csv("../data/raw/taxi_zone_lookup.csv")

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [5]:
taxi_zone.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

### Step 1: Coerce Passenger Count into Integer Data Types

In [7]:
df.dtypes.reset_index()

                    index               0
0                VendorID           int32
1    tpep_pickup_datetime  datetime64[us]
2   tpep_dropoff_datetime  datetime64[us]
3         passenger_count         float64
4           trip_distance         float64
5              RatecodeID         float64
6      store_and_fwd_flag             str
7            PULocationID           int32
8            DOLocationID           int32
9            payment_type           int64
10            fare_amount         float64
11                  extra         float64
12                mta_tax         float64
13             tip_amount         float64
14           tolls_amount         float64
15  improvement_surcharge         float64
16           total_amount         float64
17   congestion_surcharge         float64
18            Airport_fee         float64
19     cbd_congestion_fee         float64

In [15]:
df['RatecodeID'] = df['RatecodeID'].astype('Int32')
df[['RatecodeID']].sample(10)

         RatecodeID
177583            1
263016            1
3100225        <NA>
2221973           1
3451379        <NA>
2009546           1
402353            1
3494043        <NA>
1415769           1
1994265           1

In [16]:
df['passenger_count'] = df['passenger_count'].astype('Int32')
df[['passenger_count']].sample(10)

         passenger_count
3370924             <NA>
2330333                1
606883                 1
3706167             <NA>
2199000                1
973907                 1
1120261                1
2337498                1
482839                 1
2666199             <NA>

### Step 2: Remove columns with questionable pick up times (dropff time that is earlier thatn pick up time)